app:
  app_name: kampus-app-auth
  host: 0.0.0.0
  port: 5000
  api_key: edsgesagfewaFAWfgafa

database:
  host: localhost
  port: 5432
  name: kampus
  username: lvender
  password: 181205

jwt:
  secret: gdsgsdgsesesgesgvbsddc

api:
  secret: wafevewtnewstngserehybtw
